### PR TITLE
[Chart] add logic for updating/verifying helm repo, support helm install online by url.

### PR DESCRIPTION
**Pull request by zhu733756**
Signed-off-by: zhu733756 <zhu733756@kubesphere.io>

#### What type of PR is this?
/kind enhancement

#### What this PR does / why we need it:
Add logic for updating/verifying helm repo, support helm repo install online by url.
- make update-helm-repo to refresh the helm repo
- make verify-helm-repo to check the checksum of the helm repo

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Other Note

/cc

### CODE REVIEW

**Review by gnunu — COMMENTED** [review]
1) should binary charts/yurtcluster-operator.tgz be a part of commit?
2) are files moves necessary?

**Comment by zhu733756** [comment]
> 1. should binary charts/yurtcluster-operator.tgz be a part of commit?

Yeah, we can install through `helm install  https://github.com/openyurtio/yurtcluster-operator/.../yurtcluseter-operator.tgz`, by a link here.

> 2. are files moves necessary?

The script packages the subfolder, it is easy to get the whole checksum.  In addition,  the tgz file mixed the YAML  files, I think a bit not make sense.

**Comment by SataQiu** [comment]
> > 1. should binary charts/yurtcluster-operator.tgz be a part of commit?
> 
> Yeah, we can install through `helm install https://github.com/openyurtio/yurtcluster-operator/.../yurtcluseter-operator.tgz`, by a link here.

Ideally, I think we would only release the `tgz` package in every release instead of committing it into codebase.
So user can consume it by a link.

**Comment by zhu733756** [comment]
> > > 1. should binary charts/yurtcluster-operator.tgz be a part of commit?
> > 
> > 
> > Yeah, we can install through `helm install https://github.com/openyurtio/yurtcluster-operator/.../yurtcluseter-operator.tgz`, by a link here.
> 
> Ideally, I think we would only release the `tgz` package in every release instead of committing it into codebase. So user can consume it by a link.



> > > 1. should binary charts/yurtcluster-operator.tgz be a part of commit?
> > 
> > 
> > Yeah, we can install through `helm install https://github.com/openyurtio/yurtcluster-operator/.../yurtcluseter-operator.tgz`, by a link here.
> 
> Ideally, I think we would only release the `tgz` package in every release instead of committing it into codebase. So user can consume it by a link.

All right.

**Comment by SataQiu** [comment]
/close

Please download the helm chart from https://github.com/openyurtio/yurtcluster-operator/releases/download/v0.6.1/yurtcluster-operator-v0.6.1.tgz

**Pull request closed without merging**
